name: flutter_vonage_opentok_web
description: The web implementation of flutter_vonage_opentok.

version: 1.0.5

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter: { sdk: flutter }
  flutter_vonage_opentok_platform_interface: ^1.0.5
  flutter_web_plugins: { sdk: flutter }
  js: ^0.6.7

dev_dependencies:
  flutter_test: { sdk: flutter }
  my_linter: ^0.0.6

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterVonageOpentokWeb
        fileName: flutter_vonage_opentok_web.dart
