name: flutter_vonage_opentok_platform_interface
description: A common platform interface for the flutter_vonage_opentok plugin.

version: 1.0.3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter: { sdk: flutter }
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test: { sdk: flutter }
  my_linter: ^0.0.6

